# Video-optimized dataset configuration for mermaid LoRA
resolutions = [480]
enable_ar_bucket = false
frame_buckets = [16]
min_ar = 0.8
max_ar = 1.25
num_ar_buckets = 3

[[directory]]
path = 'data/input'
num_repeats = 1
